// edict/frontend/src/components/EdictBoard.tsx
import { useState } from 'react';
import { useStore, isEdict, isArchived, getPipeStatus, stateLabel, deptColor, PIPE } from '../store';
import { api, type Task } from '../api';
import { formatDashboardDateTime, getTaskTiming } from '../time';

// 排序权重
const STATE_ORDER: Record<string, number> = {
  Doing: 0, Review: 1, Assigned: 2, Menxia: 3, Zhongshu: 4,
  Taizi: 5, Inbox: 6, Blocked: 7, Next: 8, Done: 9, Cancelled: 10,
};

function MiniPipe({ task }: { task: Task }) {
  const stages = getPipeStatus(task);
  return (
    <div className="ec-pipe">
      {stages.map((s, i) => (
        <span key={s.key} style={{ display: 'contents' }}>
          <div className={`ep-node ${s.status}`}>
            <div className="ep-icon">{s.icon}</div>
            <div className="ep-name">{s.dept}</div>
          </div>
          {i < stages.length - 1 && <div className="ep-arrow">›</div>}
        </span>
      ))}
    </div>
  );
}

function EdictCard({ task }: { task: Task }) {
  const setModalTaskId = useStore((s) => s.setModalTaskId);
  const toast = useStore((s) => s.toast);
  const loadAll = useStore((s) => s.loadAll);

  const hb = task.heartbeat || { status: 'unknown', label: '⚪' };
  const stCls = 'st-' + (task.state || '');
  const deptCls = 'dt-' + (task.org || '').replace(/\s/g, '');
  const curStage = PIPE.find((_, i) => getPipeStatus(task)[i].status === 'active');
  const todos = task.todos || [];
  const todoDone = todos.filter((x) => x.status === 'completed').length;
  const todoTotal = todos.length;
  const canStop = !['Done', 'Blocked', 'Cancelled'].includes(task.state);
  const canResume = ['Blocked', 'Cancelled'].includes(task.state);
  const archived = isArchived(task);
  const isBlocked = task.block && task.block !== '无' && task.block !== '-';
  const timing = getTaskTiming(task);

  const handleAction = async (action: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (action === 'stop' || action === 'cancel') {
      // Use confirm dialog via store (will implement with ConfirmDialog)
      const reason = prompt(action === 'stop' ? '请输入叫停原因：' : '请输入取消原因：');
      if (reason === null) return;
      try {
        const r = await api.taskAction(task.id, action, reason);
        if (r.ok) { toast(r.message || '操作成功'); loadAll(); }
        else toast(r.error || '操作失败', 'err');
      } catch { toast('服务器连接失败', 'err'); }
    } else if (action === 'resume') {
      try {
        const r = await api.taskAction(task.id, 'resume', '恢复执行');
        if (r.ok) { toast(r.message || '已恢复'); loadAll(); }
        else toast(r.error || '操作失败', 'err');
      } catch { toast('服务器连接失败', 'err'); }
    }
  };

  const handleArchive = async (e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      const r = await api.archiveTask(task.id, !task.archived);
      if (r.ok) { toast(r.message || '操作成功'); loadAll(); }
      else toast(r.error || '操作失败', 'err');
    } catch { toast('服务器连接失败', 'err'); }
  };

  return (
    <div
      className={`edict-card${archived ? ' archived' : ''}`}
      onClick={() => setModalTaskId(task.id)}
    >
      <MiniPipe task={task} />
      <div className="ec-id">{task.id}</div>
      <div className="ec-title">{task.title || '(无标题)'}</div>
      <div className="ec-meta">
        <span className={`tag ${stCls}`}>{stateLabel(task)}</span>
        {task.org && <span className={`tag ${deptCls}`}>{task.org}</span>}
        {curStage && (
          <span style={{ fontSize: 11, color: 'var(--muted)' }}>
            当前: <b style={{ color: deptColor(curStage.dept) }}>{curStage.dept} · {curStage.action}</b>
          </span>
        )}
      </div>
      {task.now && task.now !== '-' && (
        <div style={{ fontSize: 11, color: 'var(--muted)', lineHeight: 1.5, marginBottom: 6 }}>
          {task.now.substring(0, 80)}
        </div>
      )}
      {(task.review_round || 0) > 0 && (
        <div style={{ fontSize: 11, marginBottom: 6 }}>
          {Array.from({ length: task.review_round || 0 }, (_, i) => (
            <span
              key={i}
              style={{
                display: 'inline-block', width: 14, height: 14, borderRadius: '50%',
                background: i < (task.review_round || 0) - 1 ? '#1a3a6a22' : 'var(--acc)22',
                border: `1px solid ${i < (task.review_round || 0) - 1 ? '#2a4a8a' : 'var(--acc)'}`,
                fontSize: 9, textAlign: 'center', lineHeight: '13px', marginRight: 2,
                color: i < (task.review_round || 0) - 1 ? '#4a6aaa' : 'var(--acc)',
              }}
            >
              {i + 1}
            </span>
          ))}
          <span style={{ color: 'var(--muted)', fontSize: 10 }}>第 {task.review_round} 轮磋商</span>
        </div>
      )}
      {todoTotal > 0 && (
        <div className="ec-todo-bar">
          <span>📋 {todoDone}/{todoTotal}</span>
          <div className="ec-todo-track">
            <div className="ec-todo-fill" style={{ width: `${Math.round((todoDone / todoTotal) * 100)}%` }} />
          </div>
          <span>{todoDone === todoTotal ? '✅ 全部完成' : '🔄 进行中'}</span>
        </div>
      )}
      <div className="ec-footer">
        <span className={`hb ${hb.status}`}>{hb.label}</span>
        {timing.durationText && (
          <span style={{ fontSize: 11, color: 'var(--muted)' }}>
            ⏱ {timing.isTerminal ? '耗时' : '已用时'} {timing.durationText}
          </span>
        )}
        {isBlocked && (
          <span className="tag" style={{ borderColor: '#ff527044', color: 'var(--danger)', background: '#200a10' }}>
            🚫 {task.block}
          </span>
        )}
        {task.eta && task.eta !== '-' && (
          <span style={{ fontSize: 11, color: 'var(--muted)' }}>📅 {formatDashboardDateTime(task.eta) || task.eta}</span>
        )}
      </div>
      <div className="ec-actions" onClick={(e) => e.stopPropagation()}>
        {canStop && (
          <>
            <button className="mini-act" onClick={(e) => handleAction('stop', e)}>⏸ 叫停</button>
            <button className="mini-act danger" onClick={(e) => handleAction('cancel', e)}>🚫 取消</button>
          </>
        )}
        {canResume && (
          <button className="mini-act" onClick={(e) => handleAction('resume', e)}>▶ 恢复</button>
        )}
        {archived && !task.archived && (
          <button className="mini-act" onClick={handleArchive}>📦 归档</button>
        )}
        {task.archived && (
          <button className="mini-act" onClick={handleArchive}>📤 取消归档</button>
        )}
      </div>
    </div>
  );
}

export default function EdictBoard() {
  const liveStatus = useStore((s) => s.liveStatus);
  const edictFilter = useStore((s) => s.edictFilter);
  const setEdictFilter = useStore((s) => s.setEdictFilter);
  const toast = useStore((s) => s.toast);
  const loadAll = useStore((s) => s.loadAll);
  const countdown = useStore((s) => s.countdown);
  const [decreeText, setDecreeText] = useState('');
  const [decreeOpen, setDecreeOpen] = useState(false);
  void countdown;

  const tasks = liveStatus?.tasks || [];
  const allEdicts = tasks.filter(isEdict);
  const activeEdicts = allEdicts.filter((t) => !isArchived(t));
  const archivedEdicts = allEdicts.filter((t) => isArchived(t));

  let edicts: Task[];
  if (edictFilter === 'active') edicts = activeEdicts;
  else if (edictFilter === 'archived') edicts = archivedEdicts;
  else edicts = allEdicts;

  edicts.sort((a, b) => (STATE_ORDER[a.state] ?? 9) - (STATE_ORDER[b.state] ?? 9));

  const unArchivedDone = allEdicts.filter((t) => !t.archived && ['Done', 'Cancelled'].includes(t.state));

  const handleArchiveAll = async () => {
    if (!confirm('将所有已完成/已取消的旨意移入归档？')) return;
    try {
      const r = await api.archiveAllDone();
      if (r.ok) { toast(`📦 ${r.count || 0} 道旨意已归档`); loadAll(); }
      else toast(r.error || '批量归档失败', 'err');
    } catch { toast('服务器连接失败', 'err'); }
  };

  const handleScan = async () => {
    try {
      const r = await api.schedulerScan();
      if (r.ok) toast(`🧭 太子巡检完成：${r.count || 0} 个动作`);
      else toast(r.error || '巡检失败', 'err');
      loadAll();
    } catch { toast('服务器连接失败', 'err'); }
  };

  const handleDecree = async () => {
    const text = decreeText.trim();
    if (!text) { toast('请输入旨意内容', 'err'); return; }
    try {
      const r = await api.createTask({
        title: text,
        org: '中书省',
        priority: '中',
      });
      if (r.ok) {
        toast(`📜 旨意已下达`, 'ok');
        setDecreeText('');
        setDecreeOpen(false);
        loadAll();
      } else {
        toast(r.error || '下旨失败', 'err');
      }
    } catch { toast('服务器连接失败', 'err'); }
  };

  return (
    <div>
      {/* Decree Input */}
      <div style={{ marginBottom: 12 }}>
        {decreeOpen ? (
          <div style={{
            background: 'var(--panel2)', border: '1px solid var(--line)',
            borderRadius: 10, padding: 14,
          }}>
            <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 8, color: 'var(--acc)' }}>
              👑 自由下旨
            </div>
            <textarea
              value={decreeText}
              onChange={(e) => setDecreeText(e.target.value)}
              placeholder="输入旨意内容，回车或点击下旨发送..."
              style={{
                width: '100%', minHeight: 60, resize: 'vertical',
                background: 'var(--bg)', border: '1px solid var(--line)',
                borderRadius: 6, padding: 8, fontSize: 13, color: 'var(--text)',
                fontFamily: 'inherit',
              }}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleDecree(); }
              }}
              autoFocus
            />
            <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end', marginTop: 8 }}>
              <button className="btn btn-g" onClick={() => setDecreeOpen(false)}
                style={{ padding: '6px 14px', fontSize: 12 }}>取消</button>
              <button className="tpl-go" onClick={handleDecree}
                style={{ padding: '6px 18px', fontSize: 12 }}>📜 下旨</button>
            </div>
          </div>
        ) : (
          <button className="tpl-go" onClick={() => setDecreeOpen(true)}
            style={{ padding: '6px 18px', fontSize: 12 }}>👑 下达旨意</button>
        )}
      </div>

      {/* Archive Bar */}
      <div className="archive-bar">
        <span className="ab-label">筛选:</span>
        {(['active', 'archived', 'all'] as const).map((f) => (
          <button
            key={f}
            className={`ab-btn ${edictFilter === f ? 'active' : ''}`}
            onClick={() => setEdictFilter(f)}
          >
            {f === 'active' ? '活跃' : f === 'archived' ? '归档' : '全部'}
          </button>
        ))}
        {unArchivedDone.length > 0 && (
          <button className="ab-btn" onClick={handleArchiveAll}>📦 一键归档</button>
        )}
        <span className="ab-count">
          活跃 {activeEdicts.length} · 归档 {archivedEdicts.length} · 共 {allEdicts.length}
        </span>
        <button className="ab-scan" onClick={handleScan}>🧭 太子巡检</button>
      </div>

      {/* Grid */}
      <div className="edict-grid">
        {edicts.length === 0 ? (
          <div className="empty" style={{ gridColumn: '1/-1' }}>
            暂无旨意<br />
            <small style={{ fontSize: 11, marginTop: 6, display: 'block', color: 'var(--muted)' }}>
              点击上方「👑 下达旨意」创建新任务
            </small>
          </div>
        ) : (
          edicts.map((t) => <EdictCard key={t.id} task={t} />)
        )}
      </div>
    </div>
  );
}

// edict/frontend/src/views/EdictBoard.vue
<template>
  <div>
    <div class="kpi-grid">
      <div class="kpi-card"><div class="kpi-label">活跃旨意</div><div class="kpi-value">{{ activeTasks.length }}</div><div class="kpi-hint">不含归档与完成</div></div>
      <div class="kpi-card"><div class="kpi-label">执行中</div><div class="kpi-value">{{ doingCount }}</div><div class="kpi-hint">六部正在办理</div></div>
      <div class="kpi-card"><div class="kpi-label">待审查</div><div class="kpi-value">{{ reviewCount }}</div><div class="kpi-hint">等待尚书省汇总</div></div>
      <div class="kpi-card"><div class="kpi-label">已完成</div><div class="kpi-value">{{ doneCount }}</div><div class="kpi-hint">可在奏折阁查看</div></div>
    </div>

    <a-card class="surface-card" :bordered="false">
      <template #title>新下旨意</template>
      <div class="form-grid">
        <a-textarea v-model:value="newTitle" :rows="3" placeholder="请输入要交办的任务、调查或开发需求" @keydown.enter.exact.prevent="createTask" />
        <div class="wrap-row">
          <a-select v-model:value="targetDept" style="width: 180px">
            <a-select-option value="">自动分派</a-select-option>
            <a-select-option value="bingbu">兵部</a-select-option>
            <a-select-option value="gongbu">工部</a-select-option>
            <a-select-option value="hubu">户部</a-select-option>
            <a-select-option value="libu">礼部</a-select-option>
            <a-select-option value="xingbu">刑部</a-select-option>
            <a-select-option value="menxia">门下省</a-select-option>
            <a-select-option value="zhongshu">中书省</a-select-option>
          </a-select>
          <a-select v-model:value="priority" style="width: 140px">
            <a-select-option value="normal">普通</a-select-option>
            <a-select-option value="high">加急</a-select-option>
            <a-select-option value="low">低优先级</a-select-option>
          </a-select>
          <a-button type="primary" :loading="creating" @click="createTask">下旨</a-button>
        </div>
      </div>
    </a-card>

    <div class="row-between" style="margin: 12px 0 8px">
      <a-segmented v-model:value="store.edictFilter" :options="filterOptions" />
      <div class="wrap-row">
        <a-button @click="scanScheduler">扫描阻塞</a-button>
        <a-button v-if="doneUnarchivedCount" @click="archiveAllDone">归档已完成/取消</a-button>
      </div>
    </div>

    <div v-if="filteredTasks.length" class="card-list">
      <a-card v-for="task in filteredTasks" :key="task.id" class="surface-card task-card" :bordered="false" @click="store.modalTaskId = task.id">
        <div class="pipe-line">
          <span v-for="stage in getPipeStatus(task)" :key="stage.key" :class="['pipe-node', stage.status]">{{ stage.icon }} {{ stage.dept }}</span>
        </div>
        <div class="row-between task-meta-line">
          <span class="muted">{{ task.id }}</span>
          <span class="muted">{{ currentStageText(task) }}</span>
        </div>
        <div class="task-title">{{ task.title }}</div>
        <p v-if="task.now" class="muted task-now">{{ task.now }}</p>
        <div class="wrap-row">
          <a-tag :color="stateColor(task.state)">{{ stateLabel(task) }}</a-tag>
          <a-tag>{{ task.org || '未分派' }}</a-tag>
          <a-tag v-if="task.review_round">第 {{ task.review_round }} 轮审查</a-tag>
          <a-tag v-if="task.block" color="error">{{ task.block }}</a-tag>
          <a-tag v-if="task.heartbeat" :color="heartbeatColor(task.heartbeat.status)">{{ task.heartbeat.label }}</a-tag>
        </div>
        <a-progress v-if="task.todos?.length" style="margin-top: 8px" :percent="todoPercent(task)" size="small" />
        <div class="row-between" style="margin-top: 8px">
          <span class="muted">{{ timing(task).durationText ? `${timing(task).isTerminal ? '总耗时' : '已用时'} ${timing(task).durationText}` : etaText(task) }}</span>
          <a-space @click.stop>
            <a-button v-if="!['Done', 'Cancelled'].includes(task.state)" size="small" danger @click="taskAction(task.id, 'stop')">叫停</a-button>
            <a-button v-if="!['Done', 'Cancelled'].includes(task.state)" size="small" danger @click="taskAction(task.id, 'cancel')">取消</a-button>
            <a-button size="small" @click="archiveTask(task, !task.archived)">{{ task.archived ? '取消归档' : '归档' }}</a-button>
            <a-button v-if="['Blocked', 'Cancelled'].includes(task.state)" size="small" type="primary" @click="taskAction(task.id, 'resume')">恢复</a-button>
          </a-space>
        </div>
      </a-card>
    </div>
    <a-empty v-else class="surface-card empty-state" description="暂无符合条件的旨意" />
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { Modal } from 'ant-design-vue';
import { api, type Task } from '../api';
import { formatDashboardDateTime, getTaskTiming } from '../time';
import { getPipeStatus, isArchived, isEdict, stateLabel, useDashboardStore } from '../stores/dashboard';

const STATE_ORDER: Record<string, number> = { Blocked: 0, Review: 1, Menxia: 2, Doing: 3, Assigned: 4, Zhongshu: 5, Taizi: 6, Next: 7, Done: 8, Cancelled: 9 };
const store = useDashboardStore();
const newTitle = ref('');
const targetDept = ref('');
const priority = ref('normal');
const creating = ref(false);
const filterOptions = [
  { label: '活跃', value: 'active' },
  { label: '已归档', value: 'archived' },
  { label: '全部', value: 'all' },
];

const edicts = computed(() => store.tasks.filter(isEdict));
const activeTasks = computed(() => edicts.value.filter((t) => !isArchived(t) && !['Done', 'Cancelled'].includes(t.state)));
const doingCount = computed(() => edicts.value.filter((t) => t.state === 'Doing').length);
const reviewCount = computed(() => edicts.value.filter((t) => ['Review', 'Menxia'].includes(t.state)).length);
const doneCount = computed(() => edicts.value.filter((t) => t.state === 'Done').length);
const doneUnarchivedCount = computed(() => edicts.value.filter((t) => !isArchived(t) && ['Done', 'Cancelled'].includes(t.state)).length);
const filteredTasks = computed(() => edicts.value
  .filter((task) => store.edictFilter === 'all' || (store.edictFilter === 'archived' ? isArchived(task) : !isArchived(task)))
  .sort((a, b) => (STATE_ORDER[a.state] ?? 50) - (STATE_ORDER[b.state] ?? 50) || String(b.updatedAt || b.updated_at || '').localeCompare(String(a.updatedAt || a.updated_at || ''))));

function etaText(task: Task) {
  return formatDashboardDateTime(task.eta) || '-';
}

function stateColor(state: string) {
  if (state === 'Done') return 'success';
  if (state === 'Blocked' || state === 'Cancelled') return 'error';
  if (state === 'Review' || state === 'Menxia') return 'warning';
  return 'processing';
}
function heartbeatColor(status: string) {
  if (status === 'active') return 'success';
  if (status === 'warn') return 'warning';
  if (status === 'stalled') return 'error';
  return 'default';
}
function todoPercent(task: Task) {
  const total = task.todos?.length || 0;
  if (!total) return 0;
  return Math.round((task.todos.filter((todo) => todo.status === 'completed').length / total) * 100);
}
function timing(task: Task) {
  return getTaskTiming(task);
}
function currentStageText(task: Task) {
  const current = getPipeStatus(task).find((stage) => stage.status === 'active');
  return current ? `${current.dept} · ${current.action}` : stateLabel(task);
}
async function createTask() {
  if (!newTitle.value.trim()) return;
  creating.value = true;
  const result = await api.createTask({ title: newTitle.value.trim(), org: '皇上', targetDept: targetDept.value || undefined, priority: priority.value });
  creating.value = false;
  if (result.ok) {
    store.toast('旨意已创建', 'ok');
    newTitle.value = '';
    await store.loadAll();
    if (result.taskId) store.modalTaskId = result.taskId;
  } else store.toast(result.error || '创建失败', 'err');
}
async function archiveTask(task: Task, archived: boolean) {
  const result = await api.archiveTask(task.id, archived);
  if (result.ok) {
    store.toast(archived ? '已归档' : '已取消归档', 'ok');
    store.loadAll();
  } else store.toast(result.error || '操作失败', 'err');
}
async function archiveAllDone() {
  Modal.confirm({ title: '归档所有已完成/取消旨意？', okText: '归档', cancelText: '取消', onOk: async () => { const r = await api.archiveAllDone(); store.toast(r.ok ? `已归档 ${r.count || 0} 条` : r.error || '归档失败', r.ok ? 'ok' : 'err'); store.loadAll(); } });
}
async function scanScheduler() {
  const r = await api.schedulerScan();
  store.toast(r.ok ? `扫描完成：${r.count || 0} 个动作` : r.error || '扫描失败', r.ok ? 'ok' : 'err');
  store.loadAll();
}
async function taskAction(taskId: string, action: string) {
  const reason = window.prompt(action === 'resume' ? '恢复说明' : action === 'stop' ? '叫停原因' : '取消原因', action === 'resume' ? '恢复执行' : '前端操作');
  if (reason === null) return;
  const r = await api.taskAction(taskId, action, reason || '前端操作');
  store.toast(r.ok ? '操作已提交' : r.error || '操作失败', r.ok ? 'ok' : 'err');
  store.loadAll();
}
</script>

<style scoped>
.task-meta-line {
  margin-top: 8px;
  font-size: 11px;
  gap: 8px;
}

.task-now {
  margin: 5px 0 7px;
  line-height: 1.45;
  overflow-wrap: anywhere;
}
</style>
