// edict/frontend/src/App.tsx
import { useEffect } from 'react';
import { useStore, TAB_DEFS, startPolling, stopPolling, startRealtime, stopRealtime, isEdict, isArchived } from './store';
import EdictBoard from './components/EdictBoard';
import MonitorPanel from './components/MonitorPanel';
import OfficialPanel from './components/OfficialPanel';
import ModelConfig from './components/ModelConfig';
import SkillsConfig from './components/SkillsConfig';
import SessionsPanel from './components/SessionsPanel';
import MemorialPanel from './components/MemorialPanel';
import TemplatePanel from './components/TemplatePanel';
import MorningPanel from './components/MorningPanel';
import TaskModal from './components/TaskModal';
// ConfirmDialog is used inside TaskModal as needed
import Toaster from './components/Toaster';
import CourtCeremony from './components/CourtCeremony';
import CourtDiscussion from './components/CourtDiscussion';

export default function App() {
  const activeTab = useStore((s) => s.activeTab);
  const setActiveTab = useStore((s) => s.setActiveTab);
  const liveStatus = useStore((s) => s.liveStatus);
  const countdown = useStore((s) => s.countdown);
  const loadAll = useStore((s) => s.loadAll);

  useEffect(() => {
    startPolling();
    startRealtime();
    return () => {
      stopRealtime();
      stopPolling();
    };
  }, []);

  // Compute header chips
  const tasks = liveStatus?.tasks || [];
  const edicts = tasks.filter(isEdict);
  const activeEdicts = edicts.filter((t) => !isArchived(t));
  const sync = liveStatus?.syncStatus;
  const syncOk = sync?.ok;
  const sessionActiveStates = ['Taizi', 'Zhongshu', 'Menxia', 'Assigned', 'Doing', 'Next', 'Review', 'Blocked'];
  const sessionActiveEdicts = tasks.filter(
    (t) => isEdict(t) && !isArchived(t) && sessionActiveStates.includes(t.state),
  );
  const monitorActiveEdicts = tasks.filter((t) => isEdict(t) && t.state !== 'Done' && t.state !== 'Next');

  // Tab badge counts
  const tabBadge = (key: string): string => {
    if (key === 'edicts') return String(activeEdicts.length);
    if (key === 'sessions') return String(sessionActiveEdicts.length);
    if (key === 'memorials') return String(edicts.filter((t) => ['Done', 'Cancelled'].includes(t.state)).length);
    if (key === 'monitor') return monitorActiveEdicts.length + '活跃';
    return '';
  };

  return (
    <div className="wrap">
      {/* ── Header ── */}
      <div className="hdr">
        <div>
          <div className="logo">三省六部 · 总控台</div>
          <div className="sub-text">Edict 三省六部 Dashboard</div>
        </div>
        <div className="hdr-r">
          <span className={`chip ${syncOk ? 'ok' : syncOk === false ? 'err' : ''}`}>
            {syncOk ? '✅ 同步正常' : syncOk === false ? '❌ 服务器未启动' : '⏳ 连接中…'}
          </span>
          <span className="chip">{activeEdicts.length} 道旨意</span>
          <button className="btn-refresh" onClick={() => loadAll()}>
            ⟳ 刷新
          </button>
          <span style={{ fontSize: 11, color: 'var(--muted)' }}>⟳ {countdown}s</span>
        </div>
      </div>

      {/* ── Tabs ── */}
      <div className="tabs">
        {TAB_DEFS.map((t) => (
          <div
            key={t.key}
            className={`tab ${activeTab === t.key ? 'active' : ''}`}
            onClick={() => setActiveTab(t.key)}
          >
            {t.icon} {t.label}
            {tabBadge(t.key) && <span className="tbadge">{tabBadge(t.key)}</span>}
          </div>
        ))}
      </div>

      {/* ── Panels ── */}
      {activeTab === 'edicts' && <EdictBoard />}
      {activeTab === 'court' && <CourtDiscussion />}
      {activeTab === 'monitor' && <MonitorPanel />}
      {activeTab === 'officials' && <OfficialPanel />}
      {activeTab === 'models' && <ModelConfig />}
      {activeTab === 'skills' && <SkillsConfig />}
      {activeTab === 'sessions' && <SessionsPanel />}
      {activeTab === 'memorials' && <MemorialPanel />}
      {activeTab === 'templates' && <TemplatePanel />}
      {activeTab === 'morning' && <MorningPanel />}

      {/* ── Overlays ── */}
      <TaskModal />
      <Toaster />
      <CourtCeremony />
    </div>
  );
}

// edict/frontend/src/App.vue
<template>
  <a-config-provider :theme="themeStore.themeConfig" :locale="zhCN" component-size="small">
    <div class="app-shell">
      <aside :class="['app-sidebar', { open: mobileNavOpen, collapsed: sidebarCollapsed }]">
        <div class="brand-block">
          <div class="brand-mark">E</div>
          <div class="brand-copy">
            <div class="brand-title">三省六部总控台</div>
            <div class="brand-sub">Edict · AI Agent 协作中枢</div>
          </div>
        </div>
        <a-button class="sidebar-collapse-btn" type="text" :title="sidebarCollapsed ? '展开侧边栏' : '折叠侧边栏'" @click="sidebarCollapsed = !sidebarCollapsed">
          {{ sidebarCollapsed ? '›' : '‹' }}
        </a-button>
        <a-menu
          class="side-menu"
          mode="inline"
          :selected-keys="[store.activeTab]"
          :inline-collapsed="sidebarCollapsed"
          @click="handleMenuClick"
        >
          <a-menu-item v-for="tab in TAB_DEFS" :key="tab.key" :title="tab.label">
            <span class="menu-icon">{{ tab.icon }}</span>
            <span>{{ tab.label }}</span>
            <a-badge v-if="tabBadge(tab.key)" class="menu-badge" :count="tabBadge(tab.key)" />
          </a-menu-item>
        </a-menu>
      </aside>

      <div class="mobile-mask" v-if="mobileNavOpen" @click="mobileNavOpen = false" />

      <main class="app-main">
        <header class="topbar">
          <div class="topbar-left">
            <a-button class="mobile-menu-btn" type="text" @click="mobileNavOpen = true">
              <MenuOutlined />
            </a-button>
            <div class="topbar-title">
              <div class="page-eyebrow">三省六部总控台 · {{ activeTabMeta?.icon }} {{ activeTabMeta?.label }}</div>
              <h1>{{ pageTitle }}</h1>
              <div class="version-line">{{ versionLabel }}</div>
            </div>
          </div>
          <div class="topbar-actions">
            <a-tag :color="syncOk ? 'success' : syncOk === false ? 'error' : 'processing'">
              {{ syncOk ? '同步正常' : syncOk === false ? '服务器未启动' : '连接中' }}
            </a-tag>
            <a-statistic class="mini-stat" title="活跃旨意" :value="store.activeEdicts.length" />
            <a-button @click="store.loadAll">刷新 · {{ store.countdown }}s</a-button>
            <a-switch
              :checked="themeStore.isDark"
              checked-children="夜"
              un-checked-children="昼"
              @change="themeStore.toggleTheme"
            />
          </div>
        </header>

        <section class="content-area">
          <EdictBoard v-if="store.activeTab === 'edicts'" />
          <CourtPanel v-else-if="store.activeTab === 'court'" />
          <MonitorPanel v-else-if="store.activeTab === 'monitor'" />
          <OfficialsPanel v-else-if="store.activeTab === 'officials'" />
          <ModelPanel v-else-if="store.activeTab === 'models'" />
          <SkillsPanel v-else-if="store.activeTab === 'skills'" />
          <SessionsPanel v-else-if="store.activeTab === 'sessions'" />
          <MemorialPanel v-else-if="store.activeTab === 'memorials'" />
          <TemplatePanel v-else-if="store.activeTab === 'templates'" />
          <MorningPanel v-else-if="store.activeTab === 'morning'" />
          <AboutPanel v-else-if="store.activeTab === 'about'" />
        </section>
      </main>

      <TaskDrawer />
      <ToastLayer />
    </div>
  </a-config-provider>
</template>

<script setup lang="ts">
import { computed, defineAsyncComponent, onMounted, onUnmounted, ref } from 'vue';
import { MenuOutlined } from '@ant-design/icons-vue';
import zhCN from 'ant-design-vue/es/locale/zh_CN';
import { TAB_DEFS, type TabKey, isArchived, isEdict, useDashboardStore } from './stores/dashboard';
import { useThemeStore } from './stores/theme';

const EdictBoard = defineAsyncComponent(() => import('./views/EdictBoard.vue'));
const CourtPanel = defineAsyncComponent(() => import('./views/CourtPanel.vue'));
const MonitorPanel = defineAsyncComponent(() => import('./views/MonitorPanel.vue'));
const OfficialsPanel = defineAsyncComponent(() => import('./views/OfficialsPanel.vue'));
const ModelPanel = defineAsyncComponent(() => import('./views/ModelPanel.vue'));
const SkillsPanel = defineAsyncComponent(() => import('./views/SkillsPanel.vue'));
const SessionsPanel = defineAsyncComponent(() => import('./views/SessionsPanel.vue'));
const MemorialPanel = defineAsyncComponent(() => import('./views/MemorialPanel.vue'));
const TemplatePanel = defineAsyncComponent(() => import('./views/TemplatePanel.vue'));
const MorningPanel = defineAsyncComponent(() => import('./views/MorningPanel.vue'));
const AboutPanel = defineAsyncComponent(() => import('./views/AboutPanel.vue'));
const TaskDrawer = defineAsyncComponent(() => import('./views/TaskDrawer.vue'));
const ToastLayer = defineAsyncComponent(() => import('./views/ToastLayer.vue'));

const store = useDashboardStore();
const themeStore = useThemeStore();
const mobileNavOpen = ref(false);
const sidebarCollapsed = ref(false);

const activeTabMeta = computed(() => TAB_DEFS.find((tab) => tab.key === store.activeTab));
const versionLabel = computed(() => store.liveStatus?.version?.label || 'V1.0.1 20260426');
const pageTitle = computed(() => {
  const map: Record<TabKey, string> = {
    edicts: '旨意运行总览',
    court: '朝堂议政',
    monitor: '省部调度监控',
    officials: '官员绩效与活跃度',
    models: '模型与派发配置',
    skills: 'Agent 技能中心',
    sessions: '执行进度追踪',
    memorials: '奏折归档库',
    templates: '常用旨意模板',
    morning: '天下要闻',
    about: '关于 Edict',
  };
  return map[store.activeTab];
});
const syncOk = computed(() => store.liveStatus?.syncStatus?.ok);

function tabBadge(key: string): number | string {
  const tasks = store.tasks;
  const edicts = tasks.filter(isEdict);
  if (key === 'edicts') return edicts.filter((t) => !isArchived(t)).length;
  if (key === 'sessions') return tasks.filter((t) => isEdict(t) && !isArchived(t) && ['Taizi', 'Zhongshu', 'Menxia', 'Assigned', 'Doing', 'Next', 'Review', 'Blocked'].includes(t.state)).length;
  if (key === 'memorials') return edicts.filter((t) => ['Done', 'Cancelled'].includes(t.state)).length;
  if (key === 'monitor') return `${edicts.filter((t) => t.state !== 'Done' && t.state !== 'Next').length}活跃`;
  return '';
}

function handleMenuClick(info: { key: string | number }) {
  selectTab(info.key as TabKey);
}

function selectTab(key: TabKey) {
  store.setActiveTab(key);
  mobileNavOpen.value = false;
}

onMounted(() => {
  store.startPolling();
  store.startRealtime();
});

onUnmounted(() => {
  store.stopRealtime();
  store.stopPolling();
});
</script>
