// edict/frontend/src/views/MonitorPanel.vue
<template>
  <div class="panel-grid monitor-panel">
    <div class="kpi-grid">
      <div class="kpi-card"><div class="kpi-label">Gateway</div><div class="kpi-value">{{ gatewayLabel }}</div><div class="kpi-hint">{{ data?.gateway?.status || (data?.checkedAt ? formatDashboardDateTime(data.checkedAt) : '等待检测') }}</div></div>
      <div class="kpi-card"><div class="kpi-label">运行中</div><div class="kpi-value">{{ byStatus.running }}</div><div class="kpi-hint">可接收任务</div></div>
      <div class="kpi-card"><div class="kpi-label">空闲</div><div class="kpi-value">{{ byStatus.idle }}</div><div class="kpi-hint">可唤醒</div></div>
      <div class="kpi-card"><div class="kpi-label">离线/未配置</div><div class="kpi-value">{{ byStatus.offline + byStatus.unconfigured }}</div><div class="kpi-hint">需要检查 AstrBot</div></div>
    </div>
    <div class="row-between">
      <h2>省部运行状态</h2>
      <a-space><a-button @click="store.loadAgentsStatus">刷新状态</a-button><a-button v-if="wakeableAgents.length" type="primary" :disabled="!gatewayAlive" @click="wakeIdle">唤醒空闲 Agent</a-button></a-space>
    </div>
    <div class="card-list">
      <a-card v-for="agent in visibleAgents" :key="agent.id" class="surface-card" :bordered="false">
        <div class="row-between">
          <div class="wrap-row"><span style="font-size: 24px">{{ agent.emoji }}</span><div><b>{{ agent.label }}</b><div class="muted">{{ agent.role }} · {{ agent.id }}</div></div></div>
          <a-tag :color="statusColor(agent.status)">{{ agent.statusLabel }}</a-tag>
        </div>
        <div class="muted" style="margin-top: 8px">最近活跃：{{ agent.lastActive ? formatDashboardDateTime(agent.lastActive) : '暂无' }}</div>
        <a-button style="margin-top: 8px" size="small" :disabled="!canWake(agent)" @click="wake(agent.id)">唤醒</a-button>
      </a-card>
    </div>

    <a-card class="surface-card" :bordered="false" title="六部值守任务">
      <div class="duty-grid">
        <div v-for="dept in DEPTS" :key="dept.id" class="duty-card">
          <div class="row-between">
            <div class="wrap-row"><span class="dept-emoji">{{ dept.emoji }}</span><div><b>{{ dept.label }}</b><div class="muted">{{ dept.role }} · {{ dept.rank }}</div></div></div>
            <a-tag :color="deptTasks(dept).blocked.length ? 'error' : deptTasks(dept).active.length ? 'processing' : 'default'">{{ deptTasks(dept).active.length }} 活跃</a-tag>
          </div>
          <div class="muted duty-model">模型：{{ officialModel(dept.id) || '-' }} · 最近活跃：{{ officialLastActive(dept.id) || '-' }}</div>
          <div v-if="deptTasks(dept).active.length" class="duty-task-list">
            <div v-for="task in deptTasks(dept).active.slice(0, 3)" :key="task.id" class="duty-task" @click="store.modalTaskId = task.id">
              <span>{{ task.id }}</span>
              <b>{{ task.title }}</b>
              <a-tag v-if="task.block" color="error">{{ task.block }}</a-tag>
            </div>
          </div>
          <a-empty v-else description="暂无活跃任务" />
        </div>
      </div>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted } from 'vue';
import { api, type AgentStatusInfo, type Task } from '../api';
import { formatDashboardDateTime } from '../time';
import { DEPTS, isArchived, isEdict, useDashboardStore } from '../stores/dashboard';
const store = useDashboardStore();
onMounted(() => { store.loadAgentsStatus(); store.loadOfficials(); });
const data = computed(() => store.agentsStatusData);
const gatewayAlive = computed(() => !!data.value?.gateway?.alive);
const gatewayLabel = computed(() => data.value?.gateway?.alive ? '在线' : data.value ? '异常' : '检测中');
const visibleAgents = computed(() => (data.value?.agents || []).filter((agent) => agent.id !== 'main'));
const byStatus = computed(() => {
  const base = { running: 0, idle: 0, offline: 0, unconfigured: 0 };
  for (const agent of visibleAgents.value) base[agent.status] += 1;
  return base;
});
const wakeableAgents = computed(() => visibleAgents.value.filter(canWake));
function statusColor(status: string) { return status === 'running' ? 'success' : status === 'idle' ? 'processing' : status === 'offline' ? 'error' : 'default'; }
function canWake(agent: AgentStatusInfo) { return gatewayAlive.value && !['running', 'unconfigured'].includes(agent.status); }
async function wake(agentId: string) { const r = await api.agentWake(agentId); store.toast(r.ok ? '唤醒请求已发送' : r.error || '唤醒失败', r.ok ? 'ok' : 'err'); store.loadAgentsStatus(); }
async function wakeIdle() { for (const agent of wakeableAgents.value) await api.agentWake(agent.id); store.toast('批量唤醒已发送', 'ok'); store.loadAgentsStatus(); }
function deptTasks(dept: typeof DEPTS[number]) {
  const active = store.tasks.filter((task) => isEdict(task) && !isArchived(task) && !['Done', 'Next', 'Cancelled'].includes(task.state) && (task.org === dept.label || task.org === dept.id));
  return { active, blocked: active.filter((task: Task) => task.state === 'Blocked' || !!task.block) };
}
function officialModel(id: string) { const official = store.officialsData?.officials.find((item) => item.id === id); return official?.model_short || official?.model; }
function officialLastActive(id: string) { const official = store.officialsData?.officials.find((item) => item.id === id); return official?.last_active ? formatDashboardDateTime(official.last_active, { showSeconds: false }) : ''; }
</script>

<style scoped>
.duty-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(min(100%, 240px), 1fr));
  gap: 8px;
}

.duty-card {
  min-width: 0;
  padding: 10px;
  background: var(--app-surface-strong);
  border: 1px solid var(--app-border);
  border-radius: 12px;
}

.dept-emoji {
  font-size: 24px;
}

.duty-model {
  margin: 6px 0;
  overflow-wrap: anywhere;
}

.duty-task-list {
  display: grid;
  gap: 6px;
}

.duty-task {
  display: grid;
  gap: 3px;
  padding: 7px;
  border-radius: 10px;
  cursor: pointer;
  overflow-wrap: anywhere;
}

.duty-task:hover {
  background: var(--app-surface);
}
</style>

// edict/frontend/src/components/MonitorPanel.tsx
import { useEffect } from 'react';
import { useStore, DEPTS, isEdict, stateLabel } from '../store';
import { api, type OfficialInfo } from '../api';
import { formatDashboardDateTime } from '../time';

export default function MonitorPanel() {
  const liveStatus = useStore((s) => s.liveStatus);
  const agentsStatusData = useStore((s) => s.agentsStatusData);
  const officialsData = useStore((s) => s.officialsData);
  const loadAgentsStatus = useStore((s) => s.loadAgentsStatus);
  const setModalTaskId = useStore((s) => s.setModalTaskId);
  const toast = useStore((s) => s.toast);

  useEffect(() => {
    loadAgentsStatus();
  }, [loadAgentsStatus]);

  const tasks = liveStatus?.tasks || [];
  const activeTasks = tasks.filter((t) => isEdict(t) && t.state !== 'Done' && t.state !== 'Next');

  // Build official map
  const offMap: Record<string, OfficialInfo> = {};
  if (officialsData?.officials) {
    officialsData.officials.forEach((o) => { offMap[o.id] = o; });
  }

  // Agent wake
  const handleWake = async (agentId: string) => {
    try {
      const r = await api.agentWake(agentId);
      toast(r.message || '唤醒指令已发出');
      setTimeout(() => loadAgentsStatus(), 30000);
    } catch { toast('唤醒失败', 'err'); }
  };

  const handleWakeAll = async () => {
    if (!agentsStatusData) return;
    const toWake = agentsStatusData.agents.filter(
      (a) => a.id !== 'main' && a.status !== 'running' && a.status !== 'unconfigured'
    );
    if (!toWake.length) { toast('所有 Agent 均已在线'); return; }
    toast(`正在唤醒 ${toWake.length} 个 Agent...`);
    for (const a of toWake) {
      try { await api.agentWake(a.id); } catch { /* ignore */ }
    }
    toast(`${toWake.length} 个唤醒指令已发出，30秒后刷新状态`);
    setTimeout(() => loadAgentsStatus(), 30000);
  };

  // Agent Status Panel
  const asData = agentsStatusData;
  const filtered = asData?.agents?.filter((a) => a.id !== 'main') || [];
  const running = filtered.filter((a) => a.status === 'running').length;
  const idle = filtered.filter((a) => a.status === 'idle').length;
  const offline = filtered.filter((a) => a.status === 'offline').length;
  const unconf = filtered.filter((a) => a.status === 'unconfigured').length;
  const gw = asData?.gateway;
  const gwCls = gw?.probe ? 'ok' : gw?.alive ? 'warn' : 'err';

  return (
    <div>
      {/* Agent Status Panel */}
      {asData && asData.ok && (
        <div className="as-panel">
          <div className="as-header">
            <span className="as-title">🔌 Agent 在线状态</span>
            <span className={`as-gw ${gwCls}`}>Agent 运行时: {gw?.status || '未知'}</span>
            <button className="btn-refresh" onClick={() => loadAgentsStatus()} style={{ marginLeft: 8 }}>
              🔄 刷新
            </button>
            {(offline + unconf > 0) && (
              <button className="btn-refresh" onClick={handleWakeAll} style={{ marginLeft: 4, borderColor: 'var(--warn)', color: 'var(--warn)' }}>
                ⚡ 全部唤醒
              </button>
            )}
          </div>
          <div className="as-grid">
            {filtered.map((a) => {
              const canWake = a.status !== 'running' && a.status !== 'unconfigured' && gw?.alive;
              return (
                <div key={a.id} className="as-card" title={`${a.role} · ${a.statusLabel}`}>
                  <div className={`as-dot ${a.status}`} />
                  <div style={{ fontSize: 22 }}>{a.emoji}</div>
                  <div style={{ fontSize: 12, fontWeight: 700 }}>{a.label}</div>
                  <div style={{ fontSize: 10, color: 'var(--muted)' }}>{a.role}</div>
                  <div style={{ fontSize: 10, color: 'var(--muted)' }}>{a.statusLabel}</div>
                  {a.lastActive ? (
                    <div style={{ fontSize: 10, color: 'var(--muted)' }}>⏰ {formatDashboardDateTime(a.lastActive)}</div>
                  ) : (
                    <div style={{ fontSize: 10, color: 'var(--muted)' }}>无活动记录</div>
                  )}
                  {canWake && (
                    <button className="as-wake-btn" onClick={(e) => { e.stopPropagation(); handleWake(a.id); }}>
                      ⚡ 唤醒
                    </button>
                  )}
                </div>
              );
            })}
          </div>
          <div className="as-summary">
            <span><span className="as-dot running" style={{ position: 'static', width: 8, height: 8 }} /> {running} 运行中</span>
            <span><span className="as-dot idle" style={{ position: 'static', width: 8, height: 8 }} /> {idle} 待命</span>
            {offline > 0 && <span><span className="as-dot offline" style={{ position: 'static', width: 8, height: 8 }} /> {offline} 离线</span>}
            {unconf > 0 && <span><span className="as-dot unconfigured" style={{ position: 'static', width: 8, height: 8 }} /> {unconf} 未配置</span>}
            <span style={{ marginLeft: 'auto', fontSize: 10, color: 'var(--muted)' }}>
              检测于 {formatDashboardDateTime(asData.checkedAt)}
            </span>
          </div>
        </div>
      )}

      {/* Duty Grid */}
      <div className="duty-grid">
        {DEPTS.map((d) => {
          const myTasks = activeTasks.filter((t) => t.org === d.label);
          const isActive = myTasks.some((t) => t.state === 'Doing');
          const isBlocked = myTasks.some((t) => t.state === 'Blocked');
          const off = offMap[d.id];
          const hb = off?.heartbeat || { status: 'idle', label: '⚪' };
          const dotCls = isBlocked ? 'blocked' : isActive ? 'busy' : hb.status === 'active' ? 'active' : 'idle';
          const statusText = isBlocked ? '⚠️ 阻塞' : isActive ? '⚙️ 执行中' : hb.status === 'active' ? '🟢 活跃' : '⚪ 候命';
          const cardCls = isBlocked ? 'blocked-card' : isActive ? 'active-card' : '';

          return (
            <div key={d.id} className={`duty-card ${cardCls}`}>
              <div className="dc-hdr">
                <span className="dc-emoji">{d.emoji}</span>
                <div className="dc-info">
                  <div className="dc-name">{d.label}</div>
                  <div className="dc-role">{d.role} · {d.rank}</div>
                </div>
                <div className="dc-status">
                  <span className={`dc-dot ${dotCls}`} />
                  <span>{statusText}</span>
                </div>
              </div>
              <div className="dc-body">
                {myTasks.length > 0 ? (
                  myTasks.map((t) => (
                    <div key={t.id} className="dc-task" onClick={() => setModalTaskId(t.id)}>
                      <div className="dc-task-id">{t.id}</div>
                      <div className="dc-task-title">{t.title || '(无标题)'}</div>
                      {t.now && t.now !== '-' && (
                        <div className="dc-task-now">{t.now.substring(0, 70)}</div>
                      )}
                      <div className="dc-task-meta">
                        <span className={`tag st-${t.state}`}>{stateLabel(t)}</span>
                        {t.block && t.block !== '无' && (
                          <span className="tag" style={{ borderColor: '#ff527044', color: 'var(--danger)' }}>🚫{t.block}</span>
                        )}
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="dc-idle">
                    <span style={{ fontSize: 20 }}>🪭</span>
                    <span>候命中</span>
                  </div>
                )}
              </div>
              <div className="dc-footer">
                <span className="dc-model">🤖 {off?.model_short || '待配置'}</span>
                {off?.last_active && <span className="dc-la">⏰ {formatDashboardDateTime(off.last_active)}</span>}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
