// edict/frontend/src/views/MorningPanel.vue
<template>
  <div class="panel-grid morning-panel">
    <a-card class="surface-card" :bordered="false">
      <template #title>天下要闻</template>
      <template #extra>
        <a-space>
          <a-button @click="openConfig">订阅配置</a-button>
          <a-button @click="store.loadMorning">刷新</a-button>
          <a-button type="primary" :loading="refreshing" @click="refreshMorning">{{ refreshing ? `采集中 ${pollCount}/24` : '立即采集' }}</a-button>
        </a-space>
      </template>
      <div class="muted">{{ store.morningBrief?.generated_at ? `生成于 ${formatDashboardDateTime(store.morningBrief.generated_at)}` : store.morningBrief?.message || '暂无数据，请点击立即采集' }}</div>
    </a-card>

    <div v-if="categories.length" class="three-col">
      <a-card v-for="[name, items] in categories" :key="name" class="surface-card news-card" :bordered="false" :title="`${categoryIcon(name)} ${name}`">
        <a-list :data-source="items" size="small">
          <template #renderItem="{ item }">
            <a-list-item class="news-item">
              <div class="news-row">
                <div class="thumb-wrap">
                  <img v-if="isHttpImage(item.image) && !brokenImages.has(item.image || '')" class="news-thumb" :src="item.image" alt="" loading="lazy" @error="markBrokenImage(item.image)" />
                  <div v-else class="thumb-fallback">{{ categoryIcon(name) }}</div>
                </div>
                <div class="news-body">
                  <div class="wrap-row news-title-row">
                    <a :href="item.link" target="_blank" rel="noreferrer" class="news-title">{{ item.title }}</a>
                    <a-tag v-if="keywordHits(item)" color="warning">关注 {{ keywordHits(item) }}</a-tag>
                  </div>
                  <p class="news-summary">{{ item.summary || item.desc || '暂无摘要' }}</p>
                  <div class="news-meta">
                    <span>{{ item.source || name }}</span>
                    <span v-if="item.pub_date">{{ formatDashboardDateTime(item.pub_date) }}</span>
                  </div>
                </div>
              </div>
              <template #actions><a :href="item.link" target="_blank" rel="noreferrer">打开</a></template>
            </a-list-item>
          </template>
        </a-list>
      </a-card>
    </div>
    <a-empty v-else class="surface-card empty-state" description="暂无天下要闻数据" />

    <a-modal v-model:open="showConfig" width="820px" title="订阅配置" :confirm-loading="saving" ok-text="保存配置" cancel-text="取消" @ok="saveConfig">
      <div class="config-form">
        <div>
          <div class="section-title">分类订阅</div>
          <div class="wrap-row">
            <a-checkable-tag v-for="cat in config.categories" :key="cat.name" :checked="cat.enabled" @change="cat.enabled = !cat.enabled">{{ cat.name }}</a-checkable-tag>
          </div>
        </div>

        <a-form layout="vertical">
          <a-form-item label="关键词"><a-textarea v-model:value="keywordText" :rows="3" placeholder="关键词，逗号分隔" /></a-form-item>
          <div class="webhook-grid">
            <a-form-item label="企业微信 webhook"><a-input v-model:value="config.wecom_webhook" placeholder="留空则不推送" /></a-form-item>
            <a-form-item label="飞书 webhook"><a-input v-model:value="config.feishu_webhook" placeholder="留空则不推送" /></a-form-item>
          </div>
        </a-form>

        <div>
          <div class="row-between custom-head">
            <div>
              <div class="section-title">自定义信息源</div>
              <div class="muted">保存后会随下一次采集一起抓取。</div>
            </div>
            <a-button @click="addFeed">添加信息源</a-button>
          </div>
          <div v-if="config.custom_feeds.length" class="feed-list">
            <div v-for="(feed, index) in config.custom_feeds" :key="index" class="feed-row">
              <a-input v-model:value="feed.name" placeholder="名称" />
              <a-input v-model:value="feed.url" placeholder="RSS/网页 URL" />
              <a-select v-model:value="feed.category" :options="categoryOptions" placeholder="分类" />
              <a-button danger @click="removeFeed(index)">删除</a-button>
            </div>
          </div>
          <a-empty v-else description="暂无自定义信息源" />
        </div>
      </div>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref, watch } from 'vue';
import { api, type SubConfig } from '../api';
import { formatDashboardDateTime } from '../time';
import { useDashboardStore } from '../stores/dashboard';

const store = useDashboardStore();
const refreshing = ref(false);
const saving = ref(false);
const showConfig = ref(false);
const keywordText = ref('');
const pollCount = ref(0);
const brokenImages = ref(new Set<string>());
let refreshTimer: ReturnType<typeof setInterval> | null = null;
const config = reactive<SubConfig>({ categories: [], keywords: [], custom_feeds: [], wecom_webhook: '', feishu_webhook: '' });

onMounted(() => store.loadMorning());
onUnmounted(() => clearRefreshTimer());

watch(() => store.subConfig, (value) => {
  if (!value) return;
  Object.assign(config, JSON.parse(JSON.stringify({ ...value, custom_feeds: value.custom_feeds || [] })));
  keywordText.value = (value.keywords || []).join(',');
}, { immediate: true });

const enabled = computed(() => new Set((config.categories || []).filter((c) => c.enabled).map((c) => c.name)));
const keywords = computed(() => (config.keywords || []).map((item) => item.trim()).filter(Boolean));
const categories = computed(() => Object.entries(store.morningBrief?.categories || {})
  .filter(([name, items]) => (!enabled.value.size || enabled.value.has(name)) && items.length)
  .map(([name, items]) => [name, [...items].sort((a, b) => keywordHits(b) - keywordHits(a))] as const));
const categoryOptions = computed(() => (config.categories || []).map((cat) => ({ label: cat.name, value: cat.name })));

function keywordHits(item: { title?: string; summary?: string; desc?: string }) {
  const text = `${item.title || ''} ${item.summary || ''} ${item.desc || ''}`.toLowerCase();
  return keywords.value.filter((keyword) => text.includes(keyword.toLowerCase())).length;
}

function categoryIcon(name: string) {
  return name.includes('AI') ? '🤖' : name.includes('军事') ? '🛡️' : name.includes('经济') ? '📈' : '📰';
}

function isHttpImage(image?: string) {
  return !!image && /^https?:\/\//i.test(image);
}

function markBrokenImage(image?: string) {
  if (!image) return;
  brokenImages.value = new Set([...brokenImages.value, image]);
}

function openConfig() {
  showConfig.value = true;
  if (!store.subConfig) store.loadSubConfig();
}

function addFeed() {
  config.custom_feeds.push({ name: '', url: '', category: config.categories[0]?.name || '综合' });
}

function removeFeed(index: number) {
  config.custom_feeds.splice(index, 1);
}

function clearRefreshTimer() {
  if (refreshTimer) clearInterval(refreshTimer);
  refreshTimer = null;
}

async function refreshMorning() {
  if (refreshing.value) return;
  const previousGeneratedAt = store.morningBrief?.generated_at || '';
  refreshing.value = true;
  pollCount.value = 0;
  clearRefreshTimer();
  const r = await api.refreshMorning();
  store.toast(r.ok ? r.message || '采集已触发' : r.error || '采集失败', r.ok ? 'ok' : 'err');
  if (!r.ok) {
    refreshing.value = false;
    return;
  }
  refreshTimer = setInterval(async () => {
    pollCount.value += 1;
    await store.loadMorning();
    const nextGeneratedAt = store.morningBrief?.generated_at || '';
    const updated = !!nextGeneratedAt && nextGeneratedAt !== previousGeneratedAt;
    if (updated || pollCount.value >= 24) {
      clearRefreshTimer();
      refreshing.value = false;
      store.toast(updated ? '天下要闻已更新' : '采集仍在进行，请稍后刷新查看', updated ? 'ok' : 'err');
    }
  }, 5000);
}

async function saveConfig() {
  saving.value = true;
  const payload: SubConfig = {
    categories: config.categories || [],
    keywords: keywordText.value.split(/[，,]/).map((x) => x.trim()).filter(Boolean),
    custom_feeds: (config.custom_feeds || []).filter((feed) => feed.name.trim() && feed.url.trim()),
    wecom_webhook: config.wecom_webhook || '',
    feishu_webhook: config.feishu_webhook || '',
    enabled: config.enabled ?? true,
  };
  const r = await api.saveMorningConfig(payload);
  saving.value = false;
  store.toast(r.ok ? '配置已保存' : r.error || '保存失败', r.ok ? 'ok' : 'err');
  if (!r.ok) return;
  showConfig.value = false;
  await store.loadMorning();
}
</script>

<style scoped>
.morning-panel :deep(.ant-card-extra) {
  max-width: 100%;
}

.news-card :deep(.ant-list-item) {
  align-items: flex-start;
}

.news-item {
  gap: 6px;
}

.news-row {
  display: flex;
  gap: 8px;
  width: 100%;
  min-width: 0;
}

.thumb-wrap {
  flex: 0 0 76px;
  width: 76px;
  height: 54px;
  overflow: hidden;
  background: var(--app-surface-strong);
  border: 1px solid var(--app-border);
  border-radius: 10px;
}

.news-thumb {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.thumb-fallback {
  display: grid;
  place-items: center;
  width: 100%;
  height: 100%;
  font-size: 22px;
}

.news-body {
  min-width: 0;
}

.news-title {
  display: block;
  color: var(--app-text);
  font-weight: 700;
  line-height: 1.35;
  overflow-wrap: anywhere;
}

.news-summary {
  margin: 4px 0;
  color: var(--app-muted);
  line-height: 1.45;
  overflow-wrap: anywhere;
}

.news-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 4px 8px;
  color: var(--app-muted);
  font-size: 11px;
}

.config-form {
  display: grid;
  gap: 12px;
}

.section-title {
  margin-bottom: 6px;
  font-weight: 700;
}

.webhook-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 8px;
}

.custom-head {
  margin-bottom: 8px;
  gap: 8px;
}

.feed-list {
  display: grid;
  gap: 7px;
}

.feed-row {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1.5fr) minmax(120px, .7fr) auto;
  gap: 6px;
}

@media (max-width: 820px) {
  .webhook-grid,
  .feed-row {
    grid-template-columns: 1fr;
  }

  .news-row {
    gap: 7px;
  }

  .thumb-wrap {
    flex-basis: 64px;
    width: 64px;
    height: 48px;
  }
}
</style>

// edict/frontend/src/components/MorningPanel.tsx
import { useEffect, useState, useRef } from 'react';
import { useStore } from '../store';
import { api } from '../api';
import type { SubConfig, MorningNewsItem } from '../api';
import { formatDashboardDateTime } from '../time';

const CAT_META: Record<string, { icon: string; color: string; desc: string }> = {
  '政治': { icon: '🏛️', color: '#6a9eff', desc: '全球政治动态' },
  '军事': { icon: '⚔️', color: '#ff5270', desc: '军事与冲突' },
  '经济': { icon: '💹', color: '#2ecc8a', desc: '经济与市场' },
  'AI大模型': { icon: '🤖', color: '#a07aff', desc: 'AI与大模型进展' },
};

const DEFAULT_CATS = ['政治', '军事', '经济', 'AI大模型'];

export default function MorningPanel() {
  const morningBrief = useStore((s) => s.morningBrief);
  const subConfig = useStore((s) => s.subConfig);
  const loadMorning = useStore((s) => s.loadMorning);
  const loadSubConfig = useStore((s) => s.loadSubConfig);
  const toast = useStore((s) => s.toast);

  const [showConfig, setShowConfig] = useState(false);
  const [localConfig, setLocalConfig] = useState<SubConfig | null>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [refreshLabel, setRefreshLabel] = useState('⟳ 立即采集');
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    loadMorning();
  }, [loadMorning]);

  useEffect(() => {
    if (subConfig) setLocalConfig(JSON.parse(JSON.stringify(subConfig)));
  }, [subConfig]);

  useEffect(() => {
    return () => {
      if (pollRef.current) clearInterval(pollRef.current);
    };
  }, []);

  const refreshNews = async () => {
    setRefreshing(true);
    setRefreshLabel('⟳ 采集中…');
    let lastDate: string | null = null;
    try {
      lastDate = morningBrief?.generated_at || null;
    } catch { /* */ }

    try {
      const r = await api.refreshMorning();
      if (!r.ok) {
        toast(r.error || '天下要闻采集后端暂未启用', 'err');
        setRefreshing(false);
        setRefreshLabel('⟳ 立即采集');
        return;
      }
      toast(r.message || '采集已触发，自动检测更新中…', 'ok');
      let count = 0;
      if (pollRef.current) clearInterval(pollRef.current);
      pollRef.current = setInterval(async () => {
        count++;
        if (count > 24) {
          clearInterval(pollRef.current!);
          pollRef.current = null;
          setRefreshing(false);
          setRefreshLabel('⟳ 立即采集');
          toast('采集超时，请重试', 'err');
          return;
        }
        try {
          const fresh = await api.morningBrief();
          if (fresh.generated_at && fresh.generated_at !== lastDate) {
            clearInterval(pollRef.current!);
            pollRef.current = null;
            setRefreshing(false);
            setRefreshLabel('⟳ 立即采集');
            loadMorning();
            toast('✅ 天下要闻已更新', 'ok');
          } else {
            setRefreshLabel(`⟳ 采集中… (${count * 5}s)`);
          }
        } catch { /* */ }
      }, 5000);
    } catch {
      toast('触发失败', 'err');
      setRefreshing(false);
      setRefreshLabel('⟳ 立即采集');
    }
  };

  // Config helpers
  const toggleCat = (name: string) => {
    if (!localConfig) return;
    const cats = [...(localConfig.categories || [])];
    const existing = cats.find((c) => c.name === name);
    if (existing) existing.enabled = !existing.enabled;
    else cats.push({ name, enabled: true });
    setLocalConfig({ ...localConfig, categories: cats });
  };

  const addKeyword = (kw: string) => {
    if (!localConfig || !kw) return;
    const kws = [...(localConfig.keywords || [])];
    if (!kws.includes(kw)) kws.push(kw);
    setLocalConfig({ ...localConfig, keywords: kws });
  };

  const removeKeyword = (i: number) => {
    if (!localConfig) return;
    const kws = [...(localConfig.keywords || [])];
    kws.splice(i, 1);
    setLocalConfig({ ...localConfig, keywords: kws });
  };

  const addFeed = (name: string, url: string, category: string) => {
    if (!localConfig || !name || !url) {
      toast('请填写源名称和URL', 'err');
      return;
    }
    const feeds = [...(localConfig.custom_feeds || [])];
    feeds.push({ name, url, category });
    setLocalConfig({ ...localConfig, custom_feeds: feeds });
  };

  const removeFeed = (i: number) => {
    if (!localConfig) return;
    const feeds = [...(localConfig.custom_feeds || [])];
    feeds.splice(i, 1);
    setLocalConfig({ ...localConfig, custom_feeds: feeds });
  };

  const saveConfig = async () => {
    if (!localConfig) return;
    try {
      const r = await api.saveMorningConfig(localConfig);
      if (r.ok) {
        const message = r.message || '订阅配置已保存';
        toast(message, 'ok');
        loadSubConfig();
      } else {
        toast(r.error || '保存失败', 'err');
      }
    } catch {
      toast('服务器连接失败', 'err');
    }
  };

  const enabledSet = localConfig
    ? new Set((localConfig.categories || []).filter((c) => c.enabled).map((c) => c.name))
    : new Set(DEFAULT_CATS);
  const userKws = (localConfig?.keywords || []).map((k) => k.toLowerCase());

  const cats = morningBrief?.categories || {};
  const dateStr = morningBrief?.date
    ? morningBrief.date.replace(/(\d{4})(\d{2})(\d{2})/, '$1年$2月$3日')
    : '';
  const totalNews = Object.values(cats).flat().length;

  return (
    <div>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <div>
          <div style={{ fontSize: 20, fontWeight: 800, marginBottom: 4 }}>🌅 天下要闻</div>
          <div style={{ fontSize: 12, color: 'var(--muted)' }}>
            {dateStr && `${dateStr} | `}
            {morningBrief?.generated_at && `采集于 ${formatDashboardDateTime(morningBrief.generated_at)} | `}
            共 {totalNews} 条要闻
          </div>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button
            className="btn btn-g"
            onClick={() => setShowConfig(!showConfig)}
            style={{ fontSize: 12, padding: '6px 14px' }}
          >
            ⚙ 订阅配置
          </button>
          <button
            className="tpl-go"
            disabled={refreshing}
            onClick={refreshNews}
            style={{ fontSize: 12, padding: '6px 14px' }}
          >
            {refreshLabel}
          </button>
        </div>
      </div>

      {/* Subscription Config */}
      {showConfig && localConfig && (
        <SubConfigPanel
          config={localConfig}
          enabledSet={enabledSet}
          onToggleCat={toggleCat}
          onAddKeyword={addKeyword}
          onRemoveKeyword={removeKeyword}
          onAddFeed={addFeed}
          onRemoveFeed={removeFeed}
          onSave={saveConfig}
          onSetWebhook={(v) => setLocalConfig({ ...localConfig, wecom_webhook: v })}
        />
      )}

      {/* News */}
      {!Object.keys(cats).length ? (
        <div className="mb-empty">
          {morningBrief?.message || '暂无数据；天下要闻采集后端暂未启用，当前仅支持保存订阅配置'}
        </div>
      ) : (
        <div className="mb-cats">
          {Object.entries(cats).map(([cat, items]) => {
            if (!enabledSet.has(cat)) return null;
            const meta = CAT_META[cat] || { icon: '📰', color: 'var(--acc)', desc: cat };
            const scored = (items as MorningNewsItem[])
              .map((item) => {
                const text = ((item.title || '') + (item.summary || '')).toLowerCase();
                const kwHits = userKws.filter((k) => text.includes(k)).length;
                return { ...item, _kwHits: kwHits };
              })
              .sort((a, b) => b._kwHits - a._kwHits);

            return (
              <div className="mb-cat" key={cat}>
                <div className="mb-cat-hdr">
                  <span className="mb-cat-icon">{meta.icon}</span>
                  <span className="mb-cat-name" style={{ color: meta.color }}>{cat}</span>
                  <span className="mb-cat-cnt">{scored.length} 条</span>
                </div>
                <div className="mb-news-list">
                  {!scored.length ? (
                    <div className="mb-empty" style={{ padding: 16 }}>暂无新闻</div>
                  ) : (
                    scored.map((item, i) => {
                      const hasImg = !!(item.image && item.image.startsWith('http'));
                      return (
                        <div
                          className="mb-card"
                          key={i}
                          onClick={() => window.open(item.link, '_blank')}
                        >
                          <div className="mb-img">
                            {hasImg ? (
                              <img
                                src={item.image}
                                onError={(e) => {
                                  (e.target as HTMLImageElement).style.display = 'none';
                                }}
                                loading="lazy"
                                alt=""
                              />
                            ) : (
                              <span>{meta.icon}</span>
                            )}
                          </div>
                          <div className="mb-info">
                            <div className="mb-headline">
                              {item.title}
                              {item._kwHits > 0 && (
                                <span
                                  style={{
                                    fontSize: 9,
                                    padding: '1px 5px',
                                    borderRadius: 999,
                                    background: '#a07aff22',
                                    color: '#a07aff',
                                    border: '1px solid #a07aff44',
                                    marginLeft: 4,
                                  }}
                                >
                                  ⭐ 关注
                                </span>
                              )}
                            </div>
                            <div className="mb-summary">{item.summary || item.desc || ''}</div>
                            <div className="mb-meta">
                              <span className="mb-source">📡 {item.source || ''}</span>
                              {item.pub_date && (
                                <span className="mb-time">{formatDashboardDateTime(item.pub_date)}</span>
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    })
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

function SubConfigPanel({
  config,
  enabledSet,
  onToggleCat,
  onAddKeyword,
  onRemoveKeyword,
  onAddFeed,
  onRemoveFeed,
  onSave,
  onSetWebhook,
}: {
  config: SubConfig;
  enabledSet: Set<string>;
  onToggleCat: (name: string) => void;
  onAddKeyword: (kw: string) => void;
  onRemoveKeyword: (i: number) => void;
  onAddFeed: (name: string, url: string, cat: string) => void;
  onRemoveFeed: (i: number) => void;
  onSave: () => void;
  onSetWebhook: (v: string) => void;
}) {
  const [newKw, setNewKw] = useState('');
  const [feedName, setFeedName] = useState('');
  const [feedUrl, setFeedUrl] = useState('');
  const [feedCat, setFeedCat] = useState(DEFAULT_CATS[0]);

  const allCats = [...DEFAULT_CATS];
  (config.categories || []).forEach((c) => {
    if (!allCats.includes(c.name)) allCats.push(c.name);
  });

  return (
    <div className="sub-config" style={{ marginBottom: 20, padding: 16, background: 'var(--panel2)', borderRadius: 12, border: '1px solid var(--line)' }}>
      <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 12 }}>⚙ 订阅配置</div>

      {/* Categories */}
      <div style={{ marginBottom: 14 }}>
        <div style={{ fontSize: 12, fontWeight: 600, marginBottom: 8 }}>订阅分类</div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {allCats.map((cat) => {
            const meta = CAT_META[cat] || { icon: '📰', color: 'var(--acc)', desc: cat };
            const on = enabledSet.has(cat);
            return (
              <div
                key={cat}
                className={`sub-cat ${on ? 'active' : ''}`}
                onClick={() => onToggleCat(cat)}
                style={{ cursor: 'pointer', padding: '6px 12px', borderRadius: 8, border: `1px solid ${on ? 'var(--acc)' : 'var(--line)'}`, display: 'flex', alignItems: 'center', gap: 6 }}
              >
                <span>{meta.icon}</span>
                <span style={{ fontSize: 12 }}>{cat}</span>
                {on && <span style={{ fontSize: 10, color: 'var(--ok)' }}>✓</span>}
              </div>
            );
          })}
        </div>
      </div>

      {/* Keywords */}
      <div style={{ marginBottom: 14 }}>
        <div style={{ fontSize: 12, fontWeight: 600, marginBottom: 8 }}>关注关键词</div>
        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 6 }}>
          {(config.keywords || []).map((kw, i) => (
            <span key={i} className="sub-kw" style={{ fontSize: 11, padding: '2px 8px', borderRadius: 4, background: 'var(--bg)', border: '1px solid var(--line)' }}>
              {kw}
              <span style={{ cursor: 'pointer', marginLeft: 4, color: 'var(--danger)' }} onClick={() => onRemoveKeyword(i)}>✕</span>
            </span>
          ))}
        </div>
        <div style={{ display: 'flex', gap: 6 }}>
          <input
            type="text"
            value={newKw}
            onChange={(e) => setNewKw(e.target.value)}
            placeholder="输入关键词"
            onKeyDown={(e) => { if (e.key === 'Enter') { onAddKeyword(newKw.trim()); setNewKw(''); } }}
            style={{ flex: 1, padding: '6px 10px', background: 'var(--bg)', border: '1px solid var(--line)', borderRadius: 6, color: 'var(--text)', fontSize: 12, outline: 'none' }}
          />
          <button className="btn btn-g" onClick={() => { onAddKeyword(newKw.trim()); setNewKw(''); }} style={{ fontSize: 11, padding: '4px 12px' }}>
            添加
          </button>
        </div>
      </div>

      {/* Custom Feeds */}
      <div style={{ marginBottom: 14 }}>
        <div style={{ fontSize: 12, fontWeight: 600, marginBottom: 8 }}>自定义信息源</div>
        {(config.custom_feeds || []).map((f, i) => (
          <div key={i} style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 4, fontSize: 11 }}>
            <span style={{ fontWeight: 600 }}>{f.name}</span>
            <span style={{ color: 'var(--muted)', flex: 1, overflow: 'hidden', textOverflow: 'ellipsis' }}>{f.url}</span>
            <span style={{ color: 'var(--acc)' }}>{f.category}</span>
            <span style={{ cursor: 'pointer', color: 'var(--danger)' }} onClick={() => onRemoveFeed(i)}>✕</span>
          </div>
        ))}
        <div style={{ display: 'flex', gap: 6, marginTop: 6 }}>
          <input placeholder="源名称" value={feedName} onChange={(e) => setFeedName(e.target.value)}
            style={{ width: 100, padding: '6px 8px', background: 'var(--bg)', border: '1px solid var(--line)', borderRadius: 6, color: 'var(--text)', fontSize: 11, outline: 'none' }} />
          <input placeholder="RSS / URL" value={feedUrl} onChange={(e) => setFeedUrl(e.target.value)}
            style={{ flex: 1, padding: '6px 8px', background: 'var(--bg)', border: '1px solid var(--line)', borderRadius: 6, color: 'var(--text)', fontSize: 11, outline: 'none' }} />
          <select value={feedCat} onChange={(e) => setFeedCat(e.target.value)}
            style={{ padding: '6px 8px', background: 'var(--bg)', border: '1px solid var(--line)', borderRadius: 6, color: 'var(--text)', fontSize: 11, outline: 'none' }}>
            {allCats.map((c) => <option key={c} value={c}>{c}</option>)}
          </select>
          <button className="btn btn-g" onClick={() => { onAddFeed(feedName, feedUrl, feedCat); setFeedName(''); setFeedUrl(''); }} style={{ fontSize: 11, padding: '4px 12px' }}>
            添加
          </button>
        </div>
      </div>

      {/* WeCom Webhook */}
      <div style={{ marginBottom: 14 }}>
        <div style={{ fontSize: 12, fontWeight: 600, marginBottom: 6 }}>企业微信 Webhook</div>
        <input
          type="text"
          value={config.wecom_webhook || config.feishu_webhook || ''}
          onChange={(e) => onSetWebhook(e.target.value)}
          placeholder="https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=..."
          style={{ width: '100%', padding: '8px 10px', background: 'var(--bg)', border: '1px solid var(--line)', borderRadius: 6, color: 'var(--text)', fontSize: 12, outline: 'none' }}
        />
      </div>

      <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
        <button className="tpl-go" onClick={onSave} style={{ fontSize: 12, padding: '6px 16px' }}>
          💾 保存配置
        </button>
      </div>
    </div>
  );
}
