// edict/frontend/src/views/TemplatePanel.vue
<template>
  <div class="panel-grid template-panel">
    <div class="row-between"><a-segmented v-model:value="store.tplCatFilter" :options="categories" /></div>
    <div class="card-list">
      <a-card v-for="tpl in filtered" :key="tpl.id" class="surface-card" :bordered="false">
        <div class="wrap-row">
          <span style="font-size: 24px">{{ tpl.icon }}</span>
          <div>
            <b>{{ tpl.name }}</b>
            <div class="muted">{{ tpl.cat }} · {{ tpl.est }} · {{ tpl.cost }}</div>
          </div>
        </div>
        <p class="muted" style="margin-top: 7px">{{ tpl.desc }}</p>
        <div class="wrap-row"><a-tag v-for="dept in tpl.depts" :key="dept">{{ dept }}</a-tag></div>
        <a-button style="margin-top: 8px" type="primary" @click="openTemplate(tpl)">使用模板</a-button>
      </a-card>
    </div>

    <a-modal v-model:open="showForm" width="820px" :title="currentTpl ? `使用模板：${currentTpl.name}` : '使用模板'" :confirm-loading="submitting" ok-text="下旨执行" cancel-text="取消" @ok="submitTemplate">
      <template v-if="currentTpl">
        <div class="template-summary">
          <div class="template-icon">{{ currentTpl.icon }}</div>
          <div>
            <b>{{ currentTpl.name }}</b>
            <p class="muted">{{ currentTpl.desc }}</p>
            <div class="wrap-row">
              <a-tag v-for="dept in currentTpl.depts" :key="dept">{{ dept }}</a-tag>
              <a-tag>{{ currentTpl.est }}</a-tag>
              <a-tag>{{ currentTpl.cost }}</a-tag>
            </div>
          </div>
        </div>

        <a-form layout="vertical" class="template-form">
          <a-form-item v-for="param in currentTpl.params" :key="param.key" :label="`${param.label}${param.required ? ' *' : ''}`">
            <a-select v-if="param.type === 'select'" v-model:value="params[param.key]" :options="(param.options || []).map((value) => ({ label: value, value }))" />
            <a-textarea v-else-if="param.type === 'textarea'" v-model:value="params[param.key]" :rows="3" />
            <a-input v-else v-model:value="params[param.key]" />
          </a-form-item>
          <div class="template-meta-grid">
            <a-form-item label="目标部门"><a-select v-model:value="targetDept" :options="deptOptions" /></a-form-item>
            <a-form-item label="优先级"><a-select v-model:value="priority" :options="priorityOptions" /></a-form-item>
          </div>
        </a-form>

        <div class="preview-block">
          <div class="row-between">
            <b>旨意预览</b>
            <a-tag>{{ preview.length }} 字</a-tag>
          </div>
          <div class="code-block">{{ preview }}</div>
        </div>
      </template>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { api } from '../api';
import { DEPTS, TEMPLATES, TPL_CATS, type Template, useDashboardStore } from '../stores/dashboard';

const store = useDashboardStore();
const categories = computed(() => TPL_CATS.map((c) => ({ label: `${c.icon} ${c.name}`, value: c.name })));
const filtered = computed(() => TEMPLATES.filter((tpl) => store.tplCatFilter === '全部' || tpl.cat === store.tplCatFilter));
const showForm = ref(false);
const submitting = ref(false);
const currentTpl = ref<Template | null>(null);
const params = reactive<Record<string, string>>({});
const targetDept = ref('bingbu');
const priority = ref('normal');

const deptOptions = computed(() => DEPTS.map((dept) => ({ label: `${dept.emoji} ${dept.label}`, value: dept.id })));
const priorityOptions = [
  { label: '普通', value: 'normal' },
  { label: '较高', value: 'high' },
  { label: '紧急', value: 'urgent' },
];
const preview = computed(() => {
  if (!currentTpl.value) return '';
  return currentTpl.value.command.replace(/\{(\w+)\}/g, (_, key) => params[key] || `{${key}}`);
});

function openTemplate(tpl: Template) {
  currentTpl.value = tpl;
  Object.keys(params).forEach((key) => delete params[key]);
  tpl.params.forEach((param) => {
    params[param.key] = param.default || param.options?.[0] || '';
  });
  targetDept.value = mapDeptName(tpl.depts[0]) || 'bingbu';
  priority.value = 'normal';
  showForm.value = true;
}

function mapDeptName(name: string | undefined) {
  if (!name) return '';
  return DEPTS.find((dept) => dept.label === name || dept.id === name)?.id || '';
}

async function submitTemplate() {
  const tpl = currentTpl.value;
  if (!tpl) return;
  const missing = tpl.params.find((param) => param.required && !String(params[param.key] || '').trim());
  if (missing) {
    store.toast(`请填写必填参数：${missing.label}`, 'err');
    return;
  }

  submitting.value = true;
  try {
    const status = await api.agentsStatus().catch(() => null);
    if (status && status.gateway && !status.gateway.alive) {
      store.toast('Agent 网关当前不可用，已继续尝试下旨', 'err');
    }
    const r = await api.createTask({
      title: preview.value,
      org: '皇上',
      targetDept: targetDept.value,
      priority: priority.value,
      templateId: tpl.id,
      params: { ...params },
    });
    if (!r.ok) {
      store.toast(r.error || '下旨失败', 'err');
      return;
    }
    store.toast(r.taskId ? `已下旨：${r.taskId}` : '已下旨', 'ok');
    showForm.value = false;
    await store.loadAll();
    store.setActiveTab('edicts');
    if (r.taskId) store.modalTaskId = r.taskId;
  } finally {
    submitting.value = false;
  }
}
</script>

<style scoped>
.template-summary {
  display: flex;
  gap: 10px;
  padding: 10px;
  background: var(--app-surface-strong);
  border: 1px solid var(--app-border);
  border-radius: 12px;
  overflow-wrap: anywhere;
}

.template-icon {
  font-size: 28px;
}

.template-form {
  margin-top: 10px;
}

.template-meta-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 8px;
}

.preview-block {
  display: grid;
  gap: 7px;
  margin-top: 2px;
}

@media (max-width: 720px) {
  .template-meta-grid {
    grid-template-columns: 1fr;
  }

  .template-summary {
    align-items: flex-start;
  }
}
</style>

// edict/frontend/src/components/TemplatePanel.tsx
import { useState } from 'react';
import { useStore, TEMPLATES, TPL_CATS } from '../store';
import type { Template } from '../store';
import { api } from '../api';

export default function TemplatePanel() {
  const tplCatFilter = useStore((s) => s.tplCatFilter);
  const setTplCatFilter = useStore((s) => s.setTplCatFilter);
  const toast = useStore((s) => s.toast);
  const loadAll = useStore((s) => s.loadAll);

  const [formTpl, setFormTpl] = useState<Template | null>(null);
  const [formVals, setFormVals] = useState<Record<string, string>>({});
  const [previewCmd, setPreviewCmd] = useState('');

  let tpls = TEMPLATES;
  if (tplCatFilter !== '全部') tpls = tpls.filter((t) => t.cat === tplCatFilter);

  const openForm = (tpl: Template) => {
    const vals: Record<string, string> = {};
    tpl.params.forEach((p) => {
      vals[p.key] = p.default || '';
    });
    setFormVals(vals);
    setFormTpl(tpl);
    setPreviewCmd('');
  };

  const buildCmd = (tpl: Template) => {
    let cmd = tpl.command;
    for (const p of tpl.params) {
      cmd = cmd.replace(new RegExp('\\{' + p.key + '\\}', 'g'), formVals[p.key] || p.default || '');
    }
    return cmd;
  };

  const preview = () => {
    if (!formTpl) return;
    setPreviewCmd(buildCmd(formTpl));
  };

  const execute = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formTpl) return;
    const cmd = buildCmd(formTpl);
    if (!cmd.trim()) {
      toast('请填写必填参数', 'err');
      return;
    }

    // Pre-check agent runtime
    try {
      const st = await api.agentsStatus();
      if (st.ok && st.gateway && !st.gateway.alive) {
        toast('⚠️ Agent 运行时未就绪，任务将无法派发！', 'err');
        if (!confirm('Agent 运行时未就绪，继续？')) return;
      }
    } catch {
      /* ignore */
    }

    if (!confirm(`确认下旨？\n\n${cmd.substring(0, 200)}${cmd.length > 200 ? '…' : ''}`)) return;

    try {
      const params: Record<string, string> = {};
      for (const p of formTpl.params) {
        params[p.key] = formVals[p.key] || p.default || '';
      }
      const r = await api.createTask({
        title: cmd.substring(0, 120),
        org: '中书省',
        targetDept: formTpl.depts[0] || '',
        priority: 'normal',
        templateId: formTpl.id,
        params,
      });
      if (r.ok) {
        toast(`📜 ${r.taskId} 旨意已下达`, 'ok');
        setFormTpl(null);
        loadAll();
      } else {
        toast(r.error || '下旨失败', 'err');
      }
    } catch {
      toast('⚠️ 服务器连接失败', 'err');
    }
  };

  return (
    <div>
      {/* Category filter */}
      <div style={{ display: 'flex', gap: 6, marginBottom: 16, flexWrap: 'wrap' }}>
        {TPL_CATS.map((c) => (
          <span
            key={c.name}
            className={`tpl-cat${tplCatFilter === c.name ? ' active' : ''}`}
            onClick={() => setTplCatFilter(c.name)}
          >
            {c.icon} {c.name}
          </span>
        ))}
      </div>

      {/* Grid */}
      <div className="tpl-grid">
        {tpls.map((t) => (
          <div className="tpl-card" key={t.id}>
            <div className="tpl-top">
              <span className="tpl-icon">{t.icon}</span>
              <span className="tpl-name">{t.name}</span>
            </div>
            <div className="tpl-desc">{t.desc}</div>
            <div className="tpl-footer">
              {t.depts.map((d) => (
                <span className="tpl-dept" key={d}>{d}</span>
              ))}
              <span className="tpl-est">
                {t.est} · {t.cost}
              </span>
              <button className="tpl-go" onClick={() => openForm(t)}>
                下旨
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Template Form Modal */}
      {formTpl && (
        <div className="modal-bg open" onClick={() => setFormTpl(null)}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <button className="modal-close" onClick={() => setFormTpl(null)}>✕</button>
            <div className="modal-body">
              <div style={{ fontSize: 11, color: 'var(--acc)', fontWeight: 700, letterSpacing: '.04em', marginBottom: 4 }}>
                圣旨模板
              </div>
              <div style={{ fontSize: 20, fontWeight: 800, marginBottom: 6 }}>
                {formTpl.icon} {formTpl.name}
              </div>
              <div style={{ fontSize: 12, color: 'var(--muted)', marginBottom: 18 }}>{formTpl.desc}</div>
              <div style={{ display: 'flex', gap: 6, marginBottom: 18, flexWrap: 'wrap' }}>
                {formTpl.depts.map((d) => (
                  <span className="tpl-dept" key={d}>{d}</span>
                ))}
                <span style={{ fontSize: 11, color: 'var(--muted)', marginLeft: 'auto' }}>
                  {formTpl.est} · {formTpl.cost}
                </span>
              </div>

              <form className="tpl-form" onSubmit={execute}>
                {formTpl.params.map((p) => (
                  <div className="tpl-field" key={p.key}>
                    <label className="tpl-label">
                      {p.label}
                      {p.required && <span style={{ color: '#ff5270' }}> *</span>}
                    </label>
                    {p.type === 'textarea' ? (
                      <textarea
                        className="tpl-input"
                        style={{ minHeight: 80, resize: 'vertical' }}
                        required={p.required}
                        value={formVals[p.key] || ''}
                        onChange={(e) => setFormVals((v) => ({ ...v, [p.key]: e.target.value }))}
                      />
                    ) : p.type === 'select' ? (
                      <select
                        className="tpl-input"
                        value={formVals[p.key] || p.default || ''}
                        onChange={(e) => setFormVals((v) => ({ ...v, [p.key]: e.target.value }))}
                      >
                        {(p.options || []).map((o) => (
                          <option key={o}>{o}</option>
                        ))}
                      </select>
                    ) : (
                      <input
                        className="tpl-input"
                        type="text"
                        required={p.required}
                        value={formVals[p.key] || ''}
                        onChange={(e) => setFormVals((v) => ({ ...v, [p.key]: e.target.value }))}
                      />
                    )}
                  </div>
                ))}

                {previewCmd && (
                  <div
                    style={{
                      background: 'var(--panel2)',
                      border: '1px solid var(--line)',
                      borderRadius: 8,
                      padding: 12,
                      marginBottom: 14,
                      fontSize: 12,
                      color: 'var(--muted)',
                    }}
                  >
                    <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text)', marginBottom: 6 }}>
                      📜 将发送给中书省的旨意：
                    </div>
                    <div style={{ whiteSpace: 'pre-wrap', lineHeight: 1.6 }}>{previewCmd}</div>
                  </div>
                )}

                <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
                  <button type="button" className="btn btn-g" onClick={preview} style={{ padding: '8px 16px', fontSize: 12 }}>
                    👁 预览旨意
                  </button>
                  <button type="submit" className="tpl-go" style={{ padding: '8px 20px', fontSize: 13 }}>
                    📜 下旨
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
